### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by idkjs** [sophiabrandt/dotfiles#1]
I am have been in dotfile hell!

I think i might just use these.

How do you install it?

**Comment by sophiabrandt** [comment]
I clone the repo and then I symlink all the files that I need.

A few folders like `dunst` or `dmenu` only change the default colors, so they probably are not needed.

The most interesting things are probably the tmux setup and vim.

**Comment by idkjs** [comment]
Thank you, @sophiabrandt
